// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://bjxdjtgedtblyjgmewyc.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqeGRqdGdlZHRibHlqZ21ld3ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI5MzUxNzQsImV4cCI6MjA0ODUxMTE3NH0.ltUV2MKccMXKlPiOHyLzLTYSWlQGI4MnDgyB0L7VgUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);